version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: kunas-comfyui_server_1
      APP_PORT: 8188
      PROXY_AUTH_ADD: "false"

  server:
    image: yanwk/comfyui-boot:cu124-slim
    init: true
    restart: on-failure
    runtime: nvidia
    environment:
      CLI_ARGS: "--listen 0.0.0.0 --port 8188"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    volumes:
      - ${APP_DATA_DIR}/storage-cache/dot-cache:/root/.cache
      - ${APP_DATA_DIR}/storage-cache/dot-config:/root/.config
      - ${APP_DATA_DIR}/storage-nodes/dot-local:/root/.local
      - ${APP_DATA_DIR}/storage-nodes/custom_nodes:/root/ComfyUI/custom_nodes
      - ${APP_DATA_DIR}/storage-models/models:/root/ComfyUI/models
      - ${APP_DATA_DIR}/storage-models/hf-hub:/root/.cache/huggingface/hub
      - ${APP_DATA_DIR}/storage-models/torch-hub:/root/.cache/torch/hub
      - ${APP_DATA_DIR}/storage-user/input:/root/ComfyUI/input
      - ${APP_DATA_DIR}/storage-user/output:/root/ComfyUI/output
      - ${APP_DATA_DIR}/storage-user/user-profile:/root/ComfyUI/user
      - ${APP_DATA_DIR}/storage-user/user-scripts:/root/user-scripts
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
