version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: kunas-kokoro-fastapi_server_1
      APP_PORT: 8880
      PROXY_AUTH_ADD: "false"

  server:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:v0.8.2
    init: true
    restart: on-failure
    environment:
      HOST: 0.0.0.0
      PORT: 8880
      USE_GPU: "false"
      DEVICE: cpu
      DOWNLOAD_MODEL: "true"
      API_LOG_LEVEL: INFO
